version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ message broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build:
      context: ./backend/api-gateway
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - payment
      - user
      - tenant
      - house
      - rabbitmq

  payment:
    build:
      context: ./backend/payment
    volumes:
      - ./backend/payment:/app
      - /app/node_modules
    ports:
      - "4003:4003"
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - tenant
      - house
      - rabbitmq

  user:
    build:
      context: ./backend/user
    volumes:
      - ./backend/user:/app
      - /app/node_modules
    ports:
      - "4004:4004"
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - rabbitmq

  tenant:
    build:
      context: ./backend/tenant
    volumes:
      - ./backend/tenant:/app
      - /app/node_modules
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - rabbitmq

  house:
    build:
      context: ./backend/house
    volumes:
      - ./backend/house:/app
      - /app/node_modules
    ports:
      - "4002:4002"
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./react-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    env_file:
      - .env
    command: npm run dev
