name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Set up Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: wama-microservices

      # 4. Authenticate with Google Container Registry
      - name: Authenticate with Google Container Registry
        run: gcloud auth configure-docker gcr.io

      # 5. Detect changed backend services
      - name: Detect changed backend services
        id: changed-services
        run: |
          echo "Detecting changed backend services..."
          CHANGED_SERVICES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'backend/(house|tenant|payment|user|api-gateway)/' | cut -d'/' -f2 | sort -u)
          
          if [ -z "$CHANGED_SERVICES" ]; then
            echo "No backend changes detected."
            echo "BACKEND_CHANGED=false" >> $GITHUB_ENV
          else
            echo "Changed backend services: $CHANGED_SERVICES"
            echo "BACKEND_CHANGED=true" >> $GITHUB_ENV
            echo "CHANGED_SERVICES=$CHANGED_SERVICES" >> $GITHUB_ENV
          fi

      # 6. Deploy changed backend services
      - name: Build and Deploy Backend Services
        if: env.BACKEND_CHANGED == 'true'
        run: |
          for SERVICE in $CHANGED_SERVICES; do
            IMAGE_NAME=gcr.io/wama-microservices/$SERVICE
            IMAGE_TAG=$(date +%Y%m%d%H%M%S)

            echo "Building and pushing image for $SERVICE..."
            docker build -t $IMAGE_NAME:$IMAGE_TAG ./backend/$SERVICE
            docker push $IMAGE_NAME:$IMAGE_TAG
            
            # Define the correct port for each service
            case $SERVICE in
              api-gateway) PORT=4000 ;;
              house) PORT=4002 ;;
              tenant) PORT=4001 ;;
              user) PORT=4004 ;;
              payment) PORT=4003 ;;
              *) PORT=3000 ;;  # Default port (fallback)
            esac

            echo "Deploying $SERVICE to Cloud Run..."
            gcloud run deploy $SERVICE \
              --image $IMAGE_NAME:$IMAGE_TAG \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated \
              --port 3000
          done

      # 7. Detect if frontend changed
      - name: Detect frontend changes
        id: frontend-changes
        run: |
          FRONTEND_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'frontend/' && echo "true" || echo "false")
          echo "FRONTEND_CHANGED=$FRONTEND_CHANGED" >> $GITHUB_ENV

      # 8. Build and Deploy Frontend if changed
      - name: Build and Deploy Frontend
        if: env.FRONTEND_CHANGED == 'true'
        run: |
          IMAGE_NAME=gcr.io/wama-microservices/frontend
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)

          echo "Building and pushing frontend image..."
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./frontend
          docker push $IMAGE_NAME:$IMAGE_TAG

          echo "Deploying frontend to Cloud Run..."
          gcloud run deploy frontend \
            --image $IMAGE_NAME:$IMAGE_TAG \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 5173